version: '3.11'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 127.0.0.1:8000'
    network_mode: host
    volumes:
      - .:/esapp
    depends_on:
      - db
  
  queue: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    command: 'python consumer.py'
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: econscope_db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbd:/var/lib/mysql
    ports:
      - 3306:3306
